### ISSUE TITLE
publish new version?

### ISSUE THREAD

**Issue by sbma44** [msimerson/maxmind-geolite-mirror#19]
@msimerson 1.0.9 includes changes to the config file to include the ASN tarball, but not the code that handles it properly -- the published version suffers from the "tar file as mmdb" issue. Could you publish a new version containing the code presently in master?

**Comment by msimerson** [comment]
I should have asked you to update CHANGES and bump the version number in your PR. I expect a test file PR soon (either from you, or perhaps me next week when I have a little extra time) and we can do a version bump and release there.

**Comment by sbma44** [comment]
Sounds good. While I have you: any objection to me adding “use strict” for
node 4 compatibility? I’m working to get some internal projects updated
given the node 4 EOL but this might smooth the way for my own internal PR.

**Comment by msimerson** [comment]
Hah, my last PR just removed `use strict` because node 4 is EOL. It doesn't hurt anything so I don't mind. Shucks, it it comes with tests I'd find it nearly impossible to say no. ;)  Also, include an update to Changes and a version bump and I'll kick out a new release.

**Comment by msimerson** [comment]
fixed by #20
